    name: Continuous Deployment
    
    on:
      push:
        branches:
          - main
    
    jobs:
      deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Use Node 16
          uses: actions/setup-node@v1
          with:
            node-version: 16.x

        - name: Install packages
          run: npm install

        - name: Run tests
          run: npm run test
          env:
            HOST: ${{ secrets.HOST }}
            PORT: ${{ secrets.PORT }}
            PGHOST_TEST: ${{ secrets.PGHOST_TEST }}
            PGUSER_TEST: ${{ secrets.PGUSER_TEST }}
            PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }}
            PGPASSWORD_TEST: ${{ secrets.PGPASSWORD_TEST }}
            PGPORT_TEST: ${{ secrets.PGPORT_TEST }}
            PGHOST: ${{ secrets.PGHOST_TEST }}
            PGUSER: ${{ secrets.PGUSER_TEST }}
            PGDATABASE: ${{ secrets.PGDATABASE_TEST }}
            PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }}
            PGPORT: ${{ secrets.PGPORT_TEST }}
            ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
            REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
            ACCESS_TOKEN_AGE: ${{ secrets.ACCESS_TOKEN_AGE }}

        - name: Install Railway
          run: npm i -g @railway/cli

        - name: Deploy
          run: railway up
          env:
            RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
